version: 2
jobs:
  test:
      - $RUN_COMMAND
workflows:
   version: 2
   nightly:
     triggers:
       - schedule:
           cron: "30 22 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - test
