version: 2

jobs:
  test:
    - $RUN_COMMAND
    
workflows:
   version: 2
   commit-workflow:
    jobs:
      - test
   scheduled-workflow:
     triggers:
       - schedule:
           cron: "40 22 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - test
