workflows:
   version: 2
   nightly:
     triggers:
       - schedule:
           cron: "20 22 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - test
