version: 2
jobs:
  build:
    override:
      - $RUN_COMMAND
workflows:
   version: 2
   nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
     jobs:
       - build
