version: 2
jobs:
  build:
    steps:
      - run: $RUN_COMMAND
      
workflows:
   version: 2
   nightly:
    triggers:
      - schedule:
          cron: "52 9 * * *"
          filters:
            branches:
              only: master
    jobs:
       - build
