version: 2
workflows:
   version: 2
   scheduled-workflow:
     triggers:
       - schedule:
           cron: "05 23 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - test
