version: 2
jobs:
  build:
    working_directory: ~/SelenideDemo
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: ~/SelenideDemo-{{ checksum "pom.xml" }}
      - run: $RUN_COMMAND

workflows:
   version: 2
   nightly:
    triggers:
      - schedule:
          cron: "12 10 * * *"
          filters:
            branches:
              only: master
    jobs:
       - build
