version: 2
jobs:
  build:
    working_directory: ~/SelenideDemo
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      dependencies:
        pre:
        - curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        - sudo dpkg -i google-chrome.deb
        - sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
        - rm google-chrome.deb
        post:
          - wget https://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar
          - java -jar selenium-server-standalone-3.4.0.jar:
                background: true
      - run: $RUN_COMMAND

workflows:
   version: 2
   nightly:
    triggers:
      - schedule:
          cron: "04 10 * * *"
          filters:
            branches:
              only: master
    jobs:
       - build
