version: 2

jobs:
  test:
    - 

workflows:
   version: 2
   scheduled-workflow:
     triggers:
       - schedule:
           cron: "40 22 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - test
