version: 2
jobs:
  build:
    working_directory: ~/SelenideDemo
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - run: $RUN_COMMAND
      
workflows:
   version: 2
   nightly:
    triggers:
      - schedule:
          cron: "58 9 * * *"
          filters:
            branches:
              only: master
    jobs:
       - build
