version: 2
jobs:
  build:
    working_directory: ~/SelenideDemo
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - run: #STABLE
          name: Install Chromedriver latest version
          command: |
            sudo apt-get update
            sudo apt-get install lsb-release libappindicator3-1
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome"|HERE/chrome" --no-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb
      - checkout
      - restore_cache:
          key: ~/SelenideDemo-{{ checksum "pom.xml" }}
      - run: $RUN_COMMAND
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/site/allure-maven-plugin
      - store_artifacts:
          path: build/reports/tests

workflows:
   version: 2
   commit:
     jobs:
      - build
   nightly:
     triggers:
       - schedule:
          # 3am UTC
          cron: "00 03 * * *"
          filters:
            branches:
              only: master
     jobs:
       - build
